apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egressgateway
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-gateway
  dependsOn:
    - name: istio-base
    - name: istiod
  chart:
    spec:
      version: 1.19.7
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 60m
  values:
    name: istio-egressgateway
    ports:
    - port: 80
      targetPort: 8080
      name: http2
      protocol: TCP
    - port: 443
      name: https
      targetPort: 8443
      protocol: TCP
    labels:
      app: istio-egressgateway
      istio: egressgateway
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    type: ClusterIP 