apiVersion: helm.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-gateway
  dependsOn:
    - name: istio-base
    - name: istiod
  chart:
    spec:
      version: "${version}"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 60m
  values:
    autoscaling:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    service:
      type: "${service:=LoadBalancer}"