apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-cni
  targetNamespace: istio-system  
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
#      version: ${chart_version}
      version: 1.19.7
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 60m