apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system  
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-cni
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
#      version: 1.20.3
      version: "${chart_version}"
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 60m