apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istiod
  dependsOn:
    - name: istio-base
  chart:
    spec:
      version: "${version}"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h0m0s
      values:
        global:
          istioNamespace: istio-system
          proxy:
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
