apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - namespace.yaml
  - repository.yaml
  - istio-version.yaml
  - istio-base.yaml
  - istiod.yaml
  - istio-gateway.yaml
#postBuild:
#  substituteFrom:
#    - kind: ConfigMap
#      name: istio-version

