apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - namespace.yaml
  - repository.yaml
  - helm-release-istio-base.yaml
  - helm-release-istiod.yaml

