apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.10.1
resources:
- namespace.yaml
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
- ./notification
- ./applicationset-controller

patches:
- path: overlays/argocd-server-service.yaml
  target:
    kind: Service
    labelSelector: "app.kubernetes.io/name=argocd-server"